export const VIEW_INFOR_BRANCH_REQUEST = "VIEW_INFOR_BRANCH_REQUEST";
export const VIEW_INFOR_BRANCH_SUCCESS = "VIEW_INFOR_BRANCH_SUCCESS";
export const VIEW_INFOR_BRANCH_ERROR = "VIEW_INFOR_BRANCH_ERROR";
