env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 9
  project: ./Back-end/tsconfig.json
plugins:
  - "@typescript-eslint"